Added DatabaseCredentials class for Postgres
PrefectHQ/prefect-postgres pull request #13
Opened 2022-11-03 13:31 UTC by crusher95

Block used to manage authentication with a database.
    Attributes:
        database: The name of the database to use.
        username: The user name used to authenticate.
        password: The password used to authenticate.
        host: The host address of the database.
        port: The port to connect to the database.
        connect_args: The options which will be passed directly to the
            DBAPI's connect() method as additional keyword arguments.
    Example:
        Load stored database credentials:
        ```python
        from prefect_postgres import DatabaseCredentials
        database_block = DatabaseCredentials.load("BLOCK_NAME")
        ```

2022-11-03 14:11 UTC, desertaxle requested changes
In addition to the specific comments left, can you please write some tests covering the new functionality and add an entry to CHANGELOG.md describing the changes?

2022-11-03 14:11 UTC, desertaxle commented on prefect_postgres/credentials.py
> +    def get_connection(self) -> connect:
I think this needs to be typed as `AsyncConnection` class.
```suggestion
    def get_connection(self) -> psycopg.AsyncConnection:
```

2022-11-03 14:11 UTC, desertaxle commented on prefect_postgres/credentials.py
> +        return psycopg.connect(
We'll want to use `AsyncConnection` here to make sure that we can execute queries and operations asynchronously.
```suggestion
        return psycopg.AsyncConnection.connect(
```

2022-11-03 14:11 UTC, desertaxle commented on prefect_postgres/credentials.py
> +            DBAPI's connect() method as additional keyword arguments.
```suggestion
           psycopg connect() method as additional keyword arguments.
```

2022-11-03 15:03 UTC, zzstoatzz commented on prefect_postgres/credentials.py
> +    connect_args: Optional[Dict[str, Any]] = Field(default=None, title="Additional Configuration", description="Additional configuration to use when creating a database connection.")
Does it make sense for these to be `Optional`? `get_connection` appears to require all of them

2022-11-03 15:23 UTC, desertaxle commented on prefect_postgres/credentials.py
> +    connect_args: Optional[Dict[str, Any]] = Field(default=None, title="Additional Configuration", description="Additional configuration to use when creating a database connection.")
Good call. We aren't accepting a connection URL so they are all required except for `connect_args` which should default to an empty dictionary.
```suggestion
    username: str = Field(default=None, description="The name of the database to use.")
    password: SecretStr = Field(default=None, description="The user name used to authenticate.")
    database: str = Field(default=..., description="The password used to authenticate.")
    host: str = Field(default=..., description="The host address of the database.")
    port: str = Field(default=..., description="The port to connect to the database.")
    connect_args: Dict[str, Any] = Field(default_factory=dict, title="Additional Configuration", description="Additional configuration to use when creating a database connection.")
```

2022-11-03 20:56 UTC, ahuang11 requested changes
Looks like a good start. Some comments regarding styling and linting

2022-11-03 20:56 UTC, ahuang11 commented on .gitignore
> +.idea/**/azureSettings.xml
If it was just one line, would this still work?
```suggestion
# PyCharm
.idea/
```

2022-11-03 20:56 UTC, ahuang11 commented on prefect_postgres/credentials.py
> +    Example:
```suggestion
    Block used to manage authentication with a PostgreSQL database.

    Attributes:
        database: The name of the database to use.
        username: The user name used to authenticate.
        password: The password used to authenticate.
        host: The host address of the database.
        port: The port to connect to the database.
        connect_args: The options which will be passed directly to the
           psycopg connect() method as additional keyword arguments.

    Example:
```

2022-11-03 20:56 UTC, ahuang11 commented on prefect_postgres/credentials.py
> +from psycopg import connect
Running `pre-commit install && pre-commit run --all` will run isort and sort this out and remove unused imports.

2022-11-03 20:56 UTC, ahuang11 commented on prefect_postgres/credentials.py
> +import psycopg
```suggestion
from psycopg import AsyncConnection
```

2022-11-03 20:56 UTC, ahuang11 commented on prefect_postgres/credentials.py
> +        return psycopg.AsyncConnection.connect(
```suggestion
        return AsyncConnection.connect(
```

2022-11-03 20:56 UTC, ahuang11 commented on prefect_postgres/credentials.py
> +            ```
```suggestion
        Returns an authenticated connection object that can be
        used to query from databases.

        Returns:
            The authenticated Psycopg3 AsyncConnection.

        Examples:
            Create an asynchronous connection to PostgreSQL using URL params.
            ```python
            from prefect import flow
            from prefect_postgres import DatabaseCredentials
            @flow
            def postgres_credentials_flow():
                postgres_credentials = DatabaseCredentials(
                    username="prefect",
                    password="prefect_password",
                    database="postgres",
                    host="localhost",
                    port=5432
                )
                conn = postgres_credentials.get_connection()
                with conn.cursor() as cur:
                    cur.execute("CREATE TABLE test (id serial PRIMARY KEY,num integer,data text)")
            postgres_credentials_flow()
            ```
```

2022-11-03 20:56 UTC, ahuang11 commented on prefect_postgres/credentials.py
> +    def get_connection(self) -> psycopg.AsyncConnection:
```suggestion
    def get_connection(self) -> AsyncConnection:
```

2022-11-04 00:11 UTC, ahuang11 commented
I was just taking a look at https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.connect and if I'm not mistaken, I don't think you can directly pass all those keyword arguments directly into `AsyncConnection.connect`.

```python
>>> import asyncio
>>> from psycopg import AsyncConnection
>>> asyncio.run(AsyncConnection.connect(database="my_database"))
Traceback (most recent call last):
  File "/Users/andrew/mambaforge/envs/hightouch2/lib/python3.9/site-packages/psycopg/conninfo.py", line 96, in _parse_conninfo
    return pq.Conninfo.parse(conninfo.encode())
  File "/Users/andrew/mambaforge/envs/hightouch2/lib/python3.9/site-packages/psycopg/pq/pq_ctypes.py", line 927, in parse
    raise exc
psycopg.OperationalError: invalid connection option "database"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrew/mambaforge/envs/hightouch2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/andrew/mambaforge/envs/hightouch2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/andrew/mambaforge/envs/hightouch2/lib/python3.9/site-packages/psycopg/connection_async.py", line 122, in connect
    conninfo = make_conninfo(**params)
  File "/Users/andrew/mambaforge/envs/hightouch2/lib/python3.9/site-packages/psycopg/conninfo.py", line 59, in make_conninfo
    _parse_conninfo(conninfo)
  File "/Users/andrew/mambaforge/envs/hightouch2/lib/python3.9/site-packages/psycopg/conninfo.py", line 98, in _parse_conninfo
    raise e.ProgrammingError(str(ex))
psycopg.ProgrammingError: invalid connection option "database"
```

2022-12-04 02:49 UTC, closed without merging